### ISSUE TITLE
Unable to run model through program

### ISSUE THREAD

**Issue by Dan4P** [microsoft/ml4f#17]
When creating tensorflow layers models like 'https://github.com/microbit-foundation/cctd-ml-machine/blob/main/src/script/mlmodels/LayersModelTrainer.ts' the program halts and does not give an error. The program halts at this point https://github.com/microsoft/ml4f/blob/19cb3389bc9925a1c94df0a27fb16d4b0531740c/src/compiler.ts#L1162. These are the models used to generate this error 'https://github.com/Dan4P/models-store'. They are saved using the code 'model.save(downloads://my-model)' and then placed into the models folder. The command used to run and get this error is 'ml4f models/my-model.json'.
Do you have any idea why this could be happening @mmoskal?

**Comment by mmoskal** [comment]
did it break recently?

**Comment by Dan4P** [comment]
I have been trying for a week or two now and i double checked right before i reported the issue aswell.

**Comment by mmoskal** [comment]
Sorry for late reply - ml4f only support Sequential models - create them with tf.sequential(). I just noticed this now and ml4f will give an error message starting with 1.10.0

It should be possible to update https://github.com/microbit-foundation/cctd-ml-machine/blob/main/src/script/mlmodels/LayersModelTrainer.ts to use tf.sequential()
